jobs:
  - name: Go service

    pool:
      vmImage: 'Ubuntu 16.04'

    variables:
      GOPATH: '$(system.defaultWorkingDirectory)/gopath'
      GOROOT: '/usr/local/go1.11'
      modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)'

    steps:
      - task: GoTool@0
        version: 1.11
      - displayName: Set Go environment up
        script: |
          mkdir -p '$(GOPATH)/pkg'
          mkdir -p '$(GOPATH)/src'
          shopt -s extglob
          mv !(gopath) $(modulePath)
      - displayName: Build
        script: |
          go build 
        workingDirectory: '$(modulePath)/services/something-in-go'

